### ISSUE TITLE
running "python3 mdblog.py" encountered error

### ISSUE THREAD

**Issue by luckypoemster** [mudhairless/python-mdblog#1]
hi。

root@racknerd-626f077:~/python-mdblog/testsite# ls
about.md  basic.json  config.json         mdblog.log
articles  clean.sh    genTestArticles.py
root@racknerd-626f077:~/python-mdblog/testsite# cat mdblog.log
2024-11-16 02:23:52,316 - mdblog - INFO - Starting run @ Sat Nov 16 02:23:52 2024
2024-11-16 02:23:52,316 - mdblog - ERROR - Unhandled Exception caught, traceback follows.
Traceback (most recent call last):
  File "/root/python-mdblog/testsite/../mdblog.py", line 500, in <module>
    main()
  File "/root/python-mdblog/testsite/../mdblog.py", line 470, in main
    loadDefaults()
  File "/root/python-mdblog/testsite/../mdblog.py", line 295, in loadDefaults
    if gconfig.has_key("pages"):
AttributeError: 'dict' object has no attribute 'has_key'
root@racknerd-626f077:~/python-mdblog/testsite#

how to fix it?
thank u!

**Comment by mudhairless** [comment]
Most likely this is an issue with how the outdated version of python this
was written for handles dictionaries. It was some time ago and I do not
recall what that version was, potentially even python 2. I am no longer
maintaining this project and I would recommend this only as an exercise to
improve one's python programming skills only.  If you just want a simple
way to make a website you should use a different static site generator.
Hugo (gohugo.io) looks pretty cool. If you do want to use this as
programming practise then you should fork it to your own repository.
